### ISSUE TITLE
Remove lock functions

### ISSUE THREAD

**Issue by bigjohnson** [ovidiucp/TinyWebServer#15]
Hello,
I've used your library and is very good, but I think there are two locks in some client data input that can hang the webserver.
I suggest the insertion of two timeout check that can unlock the functions when client don't send expected data.
I hope the code could be useful.
Thanks

Alberto

Here the diff

\> 22a23
\> #define READ_TIMEOUT 100
124a126
\>   uint32_t start_time = millis();
128a131,133
\>     if (millis() - start_time > READ_TIMEOUT) {
\>       return false;
\>     }
131a137
\>     start_time = millis();
522a529
\>   uint32_t start_time = millis();
523a531,533
\>     if (millis() - start_time > READ_TIMEOUT) {
\>     	return i < size - 1;
\>     }
530a541
\>     start_time = millis();

**Comment by bigjohnson** [comment]
Closed!

**Comment by ovidiucp** [comment]
Awesome, thanks!

On Wed, Mar 25, 2015 at 9:14 AM, Aberto Panu <notifications@github.com>
wrote:

> Closed!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ovidiucp/TinyWebServer/issues/15#issuecomment-86100721>
> .
>



-- 
This confidential email is read by the NSA (at the least).
