### ISSUE TITLE
Flash library version 4 is not available

### ISSUE THREAD

**Issue by Tombar** [ovidiucp/TinyWebServer#22]
Hello Hello

Sadly the linky to Flash library points to version 5 of the library which doesn't work on Arduino UNO.

Would you mind providing a version of the Flash version 4 library.

Regards

M

**Comment by ovidiucp** [comment]
Hi Tombar,

I was able to compile the latest Flash version 5 with Arduino 1.6.0 for Uno using the following lines added in Flash.h just after the avr/pgmspace.h is included:

    #include <avr/pgmspace.h>

    #if ARDUINO >= 150
    typedef char prog_char __attribute__((__progmem__));
    #endif

**Comment by Tombar** [comment]
Thank you sir, i will try and let you know in case of any issue.
